-- Normative Phase 1 examples. These cases intentionally precede runtime code.
-- scripts/verify_contracts.lua validates the corpus now; run.lua exercises it
-- against the implementation as each owning phase lands.

return {
  api_version = 1,

  categories = {
    "path",
    "command",
    "option",
    "buffer",
    "help",
    "function",
    "variable",
    "mapping",
    "generic",
  },

  matcher = {
    {
      id = "path-component-prefix",
      category = "path",
      query = "de/li",
      candidate = "Desktop/Library/",
      case_mode = "insensitive",
      expected = {
        matched = true,
        level = "component_prefix",
        spans = { { 0, 2 }, { 8, 10 } },
      },
    },
    {
      id = "path-hard-separator-does-not-skip",
      category = "path",
      query = "de/li",
      candidate = "Desktop/Local/Library/",
      case_mode = "insensitive",
      expected = { matched = false },
    },
    {
      id = "path-trailing-separator-expands-one-level",
      category = "path",
      query = "de/",
      candidate = "Desktop/Library/",
      case_mode = "insensitive",
      expected = {
        matched = true,
        level = "component_prefix",
        spans = { { 0, 2 } },
      },
    },
    {
      id = "path-explicit-soft-words",
      category = "path",
      query = "pa-co",
      candidate = "partial-completion",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 2 }, { 8, 10 } },
      },
    },
    {
      id = "command-camel-partial-words",
      category = "command",
      query = "te-fi-fi",
      candidate = "TelescopeFindFiles",
      case_mode = "smart",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 2 }, { 9, 11 }, { 13, 15 } },
      },
    },
    {
      id = "command-punctuation-partial-words",
      category = "command",
      query = "te-fi-fi",
      candidate = "telescope-find-files",
      case_mode = "smart",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 2 }, { 10, 12 }, { 15, 17 } },
      },
    },
    {
      id = "command-compact-initials",
      category = "command",
      query = "tff",
      candidate = "TelescopeFindFiles",
      case_mode = "smart",
      expected = {
        matched = true,
        level = "initials",
        spans = { { 0, 1 }, { 9, 10 }, { 13, 14 } },
      },
    },
    {
      id = "command-delimited-words",
      category = "command",
      query = "de-li",
      candidate = "debug-list",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 2 }, { 6, 8 } },
      },
    },
    {
      id = "option-symbol-boundaries",
      category = "option",
      query = "wi-ig-ca",
      candidate = "wild_ignore_case",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 2 }, { 5, 7 }, { 12, 14 } },
      },
    },
    {
      id = "buffer-path-profile",
      category = "buffer",
      query = "src/ini",
      candidate = "src/init.lua",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "component_prefix",
        spans = { { 0, 3 }, { 4, 7 } },
      },
    },
    {
      id = "help-symbol-boundaries",
      category = "help",
      query = "c-au",
      candidate = "cmd-autocompletion",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 1 }, { 4, 6 } },
      },
    },
    {
      id = "function-symbol-boundaries",
      category = "function",
      query = "ge-bu",
      candidate = "get_buffer",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 2 }, { 4, 6 } },
      },
    },
    {
      id = "variable-symbol-boundaries",
      category = "variable",
      query = "co-st",
      candidate = "completion.style",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 2 }, { 11, 13 } },
      },
    },
    {
      id = "mapping-angle-boundaries",
      category = "mapping",
      query = "c-w",
      candidate = "<C-W>",
      case_mode = "insensitive",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 1, 2 }, { 3, 4 } },
      },
    },
    {
      id = "generic-whitespace-words",
      category = "generic",
      query = "alpha be",
      candidate = "alpha beta gamma",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 5 }, { 6, 8 } },
      },
    },
    {
      id = "generic-no-implicit-initials",
      category = "generic",
      query = "abg",
      candidate = "alpha beta gamma",
      case_mode = "sensitive",
      expected = { matched = false },
    },
    {
      id = "generic-no-implicit-camelcase",
      category = "generic",
      query = "alBe",
      candidate = "alphaBeta",
      case_mode = "sensitive",
      expected = { matched = false },
    },
    {
      id = "loose-fallback-disabled",
      category = "command",
      query = "dgls",
      candidate = "debug-list",
      case_mode = "sensitive",
      allow_subsequence = false,
      expected = { matched = false },
    },
    {
      id = "loose-fallback-opt-in",
      category = "command",
      query = "dgls",
      candidate = "debug-list",
      case_mode = "sensitive",
      allow_subsequence = true,
      expected = {
        matched = true,
        level = "subsequence",
        spans = { { 0, 1 }, { 4, 5 }, { 6, 7 }, { 8, 9 } },
      },
    },
    {
      id = "smart-case-lowercase-folds",
      category = "command",
      query = "tff",
      candidate = "TelescopeFindFiles",
      case_mode = "smart",
      expected = {
        matched = true,
        level = "initials",
        spans = { { 0, 1 }, { 9, 10 }, { 13, 14 } },
      },
    },
    {
      id = "smart-case-uppercase-is-sensitive",
      category = "command",
      query = "tFF",
      candidate = "TelescopeFindFiles",
      case_mode = "smart",
      expected = { matched = false },
    },
    {
      id = "utf8-prefix-span",
      category = "generic",
      query = "caf",
      candidate = "café",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "prefix",
        spans = { { 0, 3 } },
      },
    },
    {
      id = "unicode-insensitive-prefix",
      category = "generic",
      query = "ÉC",
      candidate = "école",
      case_mode = "insensitive",
      expected = {
        matched = true,
        level = "prefix",
        spans = { { 0, 3 } },
      },
    },
    {
      id = "unicode-normalization-is-not-implicit",
      category = "generic",
      query = "é",
      candidate = "école",
      case_mode = "insensitive",
      expected = { matched = false },
    },
    {
      id = "emacs-wildcard",
      category = "generic",
      matching_style = "emacs",
      query = "de*li",
      candidate = "debug-list",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 2 }, { 6, 8 } },
      },
    },
    {
      id = "emacs-repeated-soft-delimiter",
      category = "generic",
      matching_style = "emacs",
      query = "de--li",
      candidate = "debug-long-list",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 2 }, { 11, 13 } },
      },
    },
    {
      id = "emacs-repeated-soft-delimiter-requires-gap",
      category = "generic",
      matching_style = "emacs",
      query = "de--li",
      candidate = "debug-list",
      case_mode = "sensitive",
      expected = { matched = false },
    },
    {
      id = "emacs-does-not-add-compact-initials",
      category = "command",
      matching_style = "emacs",
      query = "tff",
      candidate = "TelescopeFindFiles",
      case_mode = "insensitive",
      expected = { matched = false },
    },
    {
      id = "emacs-repeated-hard-delimiter",
      category = "path",
      matching_style = "emacs",
      query = "de//li",
      candidate = "Desktop/Local/Library/",
      case_mode = "insensitive",
      expected = {
        matched = true,
        level = "word_prefix",
        spans = { { 0, 2 }, { 14, 16 } },
      },
    },
    {
      id = "emacs-structural-path-components",
      category = "path",
      matching_style = "emacs",
      query = "foo/../fo/ba",
      candidate = "foo/../foo/bar/",
      case_mode = "sensitive",
      expected = {
        matched = true,
        level = "component_prefix",
        spans = { { 0, 3 }, { 4, 6 }, { 7, 9 }, { 11, 13 } },
      },
    },
  },

  ranking = {
    {
      id = "exact-before-prefix-before-word",
      category = "command",
      query = "debug-list",
      case_mode = "sensitive",
      candidates = {
        { id = "word", text = "debug-long-list", source_order = 1 },
        { id = "prefix", text = "debug-list-extra", source_order = 2 },
        { id = "exact", text = "debug-list", source_order = 3 },
      },
      expected_ids = { "exact", "prefix", "word" },
    },
    {
      id = "ambiguous-order-is-total",
      category = "command",
      query = "de-li",
      case_mode = "insensitive",
      candidates = {
        { id = "describe", text = "describe-link", source_order = 3 },
        { id = "delete", text = "delete-line", source_order = 2 },
        { id = "debug", text = "debug-list", source_order = 1 },
      },
      expected_ids = { "debug", "delete", "describe" },
    },
    {
      id = "path-children-length-then-original-text",
      category = "path",
      query = "~/d/",
      case_mode = "insensitive",
      candidates = {
        { id = "desktop-a", text = "~/Desktop/a/", source_order = 1 },
        { id = "dotfiles-b", text = "~/dotfiles/b/", source_order = 2 },
        { id = "docs-long", text = "~/docs/long-child/", source_order = 3 },
      },
      expected_ids = {
        "desktop-a",
        "dotfiles-b",
        "docs-long",
      },
    },
    {
      id = "path-children-count-unicode-characters",
      category = "path",
      query = "~/d/",
      case_mode = "insensitive",
      candidates = {
        { id = "ascii", text = "~/d/aa/", source_order = 1 },
        { id = "unicode", text = "~/d/é/", source_order = 2 },
      },
      expected_ids = { "unicode", "ascii" },
    },
    {
      id = "source-order-final-tie-break",
      category = "generic",
      query = "same",
      case_mode = "sensitive",
      candidates = {
        { id = "second", text = "same", source_order = 2 },
        { id = "first", text = "same", source_order = 1 },
      },
      expected_ids = { "first", "second" },
    },
    {
      id = "emacs-cycle-order-is-character-length-then-original-text",
      category = "generic",
      matching_style = "emacs",
      query = "de-li",
      case_mode = "sensitive",
      candidates = {
        { id = "long", text = "debug-long-list", source_order = 1 },
        { id = "describe", text = "describe-link", source_order = 2 },
        { id = "delete", text = "delete-line", source_order = 3 },
        { id = "debug", text = "debug-list", source_order = 4 },
      },
      expected_ids = { "debug", "delete", "describe", "long" },
    },
  },

  replacements = {
    {
      id = "midline-command-suffix",
      source_text = "edit ~/de/li | keepalt",
      cursor_byte = 12,
      query = "~/de/li",
      replacement = { start_byte = 5, end_byte = 12 },
      insert_text = "~/Desktop/Library/",
      expected_text = "edit ~/Desktop/Library/ | keepalt",
      expected_cursor_byte = 23,
    },
    {
      id = "literal-apostrophe",
      source_text = "edit O'Re | keepalt",
      cursor_byte = 9,
      query = "O'Re",
      replacement = { start_byte = 5, end_byte = 9 },
      insert_text = [[O\'Reilly]],
      expected_text = [[edit O\'Reilly | keepalt]],
      expected_cursor_byte = 14,
    },
    {
      id = "escaped-space",
      source_text = [[edit My\ Do | keepalt]],
      cursor_byte = 11,
      query = "My Do",
      replacement = { start_byte = 5, end_byte = 11 },
      insert_text = [[My\ Documents]],
      expected_text = [[edit My\ Documents | keepalt]],
      expected_cursor_byte = 18,
    },
    {
      id = "cursor-inside-token-replaces-tail",
      source_text = "edit ~/de/li.txt | keepalt",
      cursor_byte = 12,
      query = "~/de/li",
      replacement = { start_byte = 5, end_byte = 16 },
      insert_text = "~/Desktop/license.txt",
      expected_text = "edit ~/Desktop/license.txt | keepalt",
      expected_cursor_byte = 26,
    },
    {
      id = "utf8-byte-range",
      source_text = "edit café | keepalt",
      cursor_byte = 10,
      query = "café",
      replacement = { start_byte = 5, end_byte = 10 },
      insert_text = "cafétéria",
      expected_text = "edit cafétéria | keepalt",
      expected_cursor_byte = 16,
    },
  },

  paths = {
    {
      id = "absolute-root",
      input = "/us/lo",
      context = { cwd = "/work/project", home = "/home/alice", env = {}, platform = "posix" },
      expected = { status = "ok", root_kind = "absolute", root_text = "/", scan_root = "/", remainder = "us/lo" },
    },
    {
      id = "home-root",
      input = "~/de/li",
      context = { cwd = "/work/project", home = "/home/alice", env = {}, platform = "posix" },
      expected = {
        status = "ok",
        root_kind = "home",
        root_text = "~/",
        scan_root = "/home/alice",
        remainder = "de/li",
      },
    },
    {
      id = "dot-root",
      input = "./src/mo",
      context = { cwd = "/work/project", home = "/home/alice", env = {}, platform = "posix" },
      expected = {
        status = "ok",
        root_kind = "cwd",
        root_text = "./",
        scan_root = "/work/project",
        remainder = "src/mo",
      },
    },
    {
      id = "parent-root",
      input = "../shared/mo",
      context = { cwd = "/work/project", home = "/home/alice", env = {}, platform = "posix" },
      expected = {
        status = "ok",
        root_kind = "parent",
        root_text = "../",
        scan_root = "/work",
        remainder = "shared/mo",
      },
    },
    {
      id = "relative-root",
      input = "src/mo",
      context = { cwd = "/work/project", home = "/home/alice", env = {}, platform = "posix" },
      expected = {
        status = "ok",
        root_kind = "relative",
        root_text = "",
        scan_root = "/work/project",
        remainder = "src/mo",
      },
    },
    {
      id = "environment-root",
      input = "$WORKSPACE/src/mo",
      context = {
        cwd = "/work/project",
        home = "/home/alice",
        env = { WORKSPACE = "/srv/workspace" },
        platform = "posix",
      },
      expected = {
        status = "ok",
        root_kind = "environment",
        root_text = "$WORKSPACE/",
        scan_root = "/srv/workspace",
        remainder = "src/mo",
      },
    },
    {
      id = "braced-relative-environment-root",
      input = "${VENDOR}/src/mo",
      context = { cwd = "/work/project", home = "/home/alice", env = { VENDOR = "vendor" }, platform = "posix" },
      expected = {
        status = "ok",
        root_kind = "environment",
        root_text = "${VENDOR}/",
        scan_root = "/work/project/vendor",
        remainder = "src/mo",
      },
    },
    {
      id = "undefined-environment-root",
      input = "$MISSING/src/mo",
      context = { cwd = "/work/project", home = "/home/alice", env = {}, platform = "posix" },
      expected = { status = "error", error_code = "undefined_environment_variable", original = "$MISSING/src/mo" },
    },
    {
      id = "named-home-is-reserved",
      input = "~bob/src/mo",
      context = { cwd = "/work/project", home = "/home/alice", env = {}, platform = "posix" },
      expected = { status = "error", error_code = "unsupported_root", original = "~bob/src/mo" },
    },
    {
      id = "windows-drive-is-not-relative-on-posix",
      input = [[C:\Users\alice\de\li]],
      context = { cwd = "/work/project", home = "/home/alice", env = {}, platform = "posix" },
      expected = { status = "error", error_code = "unsupported_root", original = [[C:\Users\alice\de\li]] },
    },
    {
      id = "unc-is-not-relative-on-posix",
      input = [[\\server\share\de\li]],
      context = { cwd = "/work/project", home = "/home/alice", env = {}, platform = "posix" },
      expected = { status = "error", error_code = "unsupported_root", original = [[\\server\share\de\li]] },
    },
    {
      id = "windows-drive-root",
      input = [[C:\Users\alice\de\li]],
      context = { cwd = [[D:\work\project]], home = [[C:\Users\alice]], env = {}, platform = "windows" },
      expected = {
        status = "ok",
        root_kind = "drive",
        root_text = [[C:\]],
        scan_root = "C:/",
        remainder = [[Users\alice\de\li]],
      },
    },
    {
      id = "windows-forward-drive-root",
      input = "c:/Users/alice/de/li",
      context = { cwd = [[D:\work\project]], home = [[C:\Users\alice]], env = {}, platform = "windows" },
      expected = {
        status = "ok",
        root_kind = "drive",
        root_text = "c:/",
        scan_root = "C:/",
        remainder = "Users/alice/de/li",
      },
    },
    {
      id = "windows-unc-root",
      input = [[\\server\share\de\li]],
      context = { cwd = [[C:\work\project]], home = [[C:\Users\alice]], env = {}, platform = "windows" },
      expected = {
        status = "ok",
        root_kind = "unc",
        root_text = [[\\server\share\]],
        scan_root = "//server/share",
        remainder = [[de\li]],
      },
    },
    {
      id = "windows-home-root",
      input = [[~\de\li]],
      context = { cwd = [[D:\work\project]], home = [[C:\Users\alice]], env = {}, platform = "windows" },
      expected = {
        status = "ok",
        root_kind = "home",
        root_text = [[~\]],
        scan_root = "C:/Users/alice",
        remainder = [[de\li]],
      },
    },
    {
      id = "windows-drive-relative-is-reserved",
      input = [[C:de\li]],
      context = { cwd = [[C:\work\project]], home = [[C:\Users\alice]], env = {}, platform = "windows" },
      expected = { status = "error", error_code = "unsupported_root", original = [[C:de\li]] },
    },
  },

  path_resolution = {
    {
      id = "symlink-spelling-is-preserved",
      input = "~/li/mo",
      fixture = {
        link_name = "link",
        target_name = "real",
        file_name = "module.lua",
      },
      expected_insert_text = "~/link/module.lua",
      expected_physical_suffix = "/real/module.lua",
    },
  },

  api = {
    {
      id = "public-streaming-provider-contract",
      provider_name = "phase1_contract_static",
      request = {
        api_version = 1,
        category = "generic",
        query = "alp",
        provider = "phase1_contract_static",
        case_mode = "sensitive",
        allow_subsequence = false,
        limit = 10,
      },
      chunks = {
        {
          { id = "prefix", label = "alphabet", insert_text = "alphabet", kind = "value", source_order = 2 },
        },
        {
          { id = "exact", label = "alp", insert_text = "alp", kind = "value", source_order = 1 },
        },
      },
      expected = {
        api_version = 1,
        final_ids = { "exact", "prefix" },
        terminal_count = 1,
      },
    },
  },

  sessions = {
    {
      id = "late-generation-is-discarded",
      current_generation = 2,
      event = { generation = 1, kind = "provider_emit" },
      expected = "discard",
    },
    {
      id = "current-generation-is-observed",
      current_generation = 2,
      event = { generation = 2, kind = "provider_emit" },
      expected = "observe",
    },
    {
      id = "accept-rejects-changed-line",
      request_snapshot = { source_text = "edit ~/de", cursor_byte = 9, generation = 3 },
      live_context = { source_text = "edit ~/dev", cursor_byte = 10, generation = 4 },
      expected = "stale_context",
    },
    {
      id = "cancelled-request-is-silent",
      current_generation = 4,
      cancelled = true,
      event = { generation = 4, kind = "provider_done" },
      expected = "discard",
    },
  },
}
