assert(vim.fn.has("nvim-0.12") == 1)
assert(vim.g.loaded_partial_completion == 1)

local completion = require("partial_completion")
assert(completion.api_version == 1)
assert(package.loaded["telescope"] == nil)
assert(package.loaded["blink.cmp"] == nil)
assert(package.loaded["cmp"] == nil)
assert(package.loaded["partial_completion.adapters.native"] == nil)
assert(package.loaded["partial_completion.adapters"] == nil)
assert(package.loaded["partial_completion.adapters.telescope"] == nil)
assert(package.loaded["partial_completion.adapters.blink"] == nil)
assert(package.loaded["partial_completion.adapters.nvim_cmp"] == nil)
assert(vim.fn.exists(":PartialCompletionEnable") == 2)
assert(vim.fn.exists(":PartialCompletionDisable") == 2)
assert(vim.fn.exists(":PartialCompletionToggle") == 2)

vim.cmd.runtime("plugin/partial-completion.lua")
assert(vim.g.loaded_partial_completion == 1)
completion.setup({})
assert(package.loaded["partial_completion.adapters.native"] == nil)
assert(package.loaded["partial_completion.adapters"] == nil)
assert(package.loaded["partial_completion.adapters.telescope"] == nil)
assert(package.loaded["partial_completion.adapters.blink"] == nil)
assert(package.loaded["partial_completion.adapters.nvim_cmp"] == nil)
assert(package.loaded["telescope"] == nil)
assert(package.loaded["blink.cmp"] == nil)
assert(package.loaded["cmp"] == nil)

local health = require("partial_completion.health")
local health_report = health.report()
for _, item in ipairs(health_report) do
  assert(item.status ~= "error", item.name .. ": " .. item.message)
end
assert(package.loaded["telescope"] == nil)
assert(package.loaded["blink.cmp"] == nil)
assert(package.loaded["cmp"] == nil)

print("Isolated Neovim startup passed")
