require("tests.helpers.runner").run({
  label = "Unit/property tests",
  patterns = { "tests/unit/*_spec.lua", "tests/property/*_spec.lua" },
  required_files = {
    "tests/property/hardening_property_spec.lua",
    "tests/property/matcher_property_spec.lua",
    "tests/unit/adapters_spec.lua",
    "tests/unit/blink_spec.lua",
    "tests/unit/boundaries_spec.lua",
    "tests/unit/cache_spec.lua",
    "tests/unit/cmdline_spec.lua",
    "tests/unit/engine_spec.lua",
    "tests/unit/filesystem_spec.lua",
    "tests/unit/matcher_spec.lua",
    "tests/unit/native_spec.lua",
    "tests/unit/nvim_cmp_spec.lua",
    "tests/unit/observability_spec.lua",
    "tests/unit/session_spec.lua",
    "tests/unit/telescope_spec.lua",
    "tests/unit/utf8_spec.lua",
  },
  minimum_files = 16,
  minimum_tests = 104,
  allowed_load_namespaces = { "partial-completion.native" },
})
